# Generated by Django 6.0.4 on 2026-07-02 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0002_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aprobacion', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Reprobado', 'Reprobado')], max_length=15)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info.cursos')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Info.tecnico')),
            ],
        ),
    ]
