# Generated by Django 6.0.4 on 2026-07-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0003_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
